### ISSUE TITLE
New some help in debugging the intellij docker deployment plugin

### ISSUE THREAD

**Issue by borntorock** [adersberger/intellij-docker-tutorial#1]
@adersberger Hi,  I'm working with Intellij 15 and docker deployment plugin (docker v1.12.5 installed via docker machine on host system which includes api v1.24).

Docker Integration version is 1.7.6 and IDE is using JAVA 7.

I'm facing the issue Failed to deploy 'demo-container5 Image Id: 67591570dd29': com.github.dockerjava.api.BadRequestException: {"message":"starting container with non-empty request body was deprecated since v1.10 and removed in v1.12"}

Even after reading the comments of all the folks in this issue, not able to figure out the solution. Has the new api version being taken care of in the docker-java source code?

Would highly appreciate to hear back from you, on how shall I resolve this issue.

Not sure how can I find the docker java version. The docker-java community directed me to check with Jetbrains community but I didn't even find out the docker plugin source code on Github.

**Comment by christhomas** [comment]
I have the exact same problem starting today
